### ISSUE TITLE
Not working on Mac Spaces / Desktops

### ISSUE THREAD

**Issue by justadandak** [peterklingelhofer/exhale#29]
Superb app and was excited to see it / play - installed and set up - then switched to another space / desktop on my MacBook (see https://support.apple.com/en-gb/guide/mac-help/mh14112/mac) and didn't work. Reporting for bigger brains to sort out (or maybe it's just me?). Looks ace though!

**Comment by peterklingelhofer** [comment]
You are totally right. I'll try to get this fixed!

**Comment by peterklingelhofer** [comment]
Submitted the latest build to the Apple app store, they will review it and the update should be available in about a day or so. Hopefully it fixes your issue, it seems to be working well for me over here - when I change spaces the visualization follows me.

**Comment by peterklingelhofer** [comment]
@justadandak latest is available at in the Apple App Store. Let me know if this resolves your issues, and I'll close this. The opacity isn't retained during the animation if you're swiping between spaces, and only uses opacity after the swiping animation completes, but this is a decent first pass I hope.

**Comment by justadandak** [comment]
> @justadandak latest is available at in the Apple App Store. Let me know if this resolves your issues, and I'll close this. The opacity isn't retained during the animation if you're swiping between spaces, and only uses opacity after the swiping animation completes, but this is a decent first pass I hope.

Appreciate the follow up Peter plus your work on the fix - can confirm it works as you described. As you mentioned it also adds in another black space whilst transitioning between spaces (for about half a second) which does disrupt the workflow visually a tad - holler when this is fixed and will definitely come back and use (bit jarring at the moment). Appreciate your time!

**Comment by peterklingelhofer** [comment]
I've reverted the spaces support change in the latest version because you're right, it's pretty disruptive to your flow. It doesn't seem that Apple supports window opacity for windows present in all spaces during that swipe transition period for some reason. Will wait to re-implement this until we can eliminate that bug.
