### ISSUE TITLE
iOS/iPadOS support

### ISSUE THREAD

**Issue by berceanu** [peterklingelhofer/exhale#33]
Great app!
Are you considering adding support for iOS/iPadOS as well?

**Comment by peterklingelhofer** [comment]
Thank you. I looked into iOS/iPad about a year ago and it seemed to require a jailbreak since Apple doesn't let you control the screen as an overlay natively, unfortunately.

**Comment by peterklingelhofer** [comment]
https://www.reddit.com/r/iOSProgramming/s/bAR97IkiES

It looks like this may be possible now, potentially. This would probably be a pretty big lift but I'll start investigating further.
